### ISSUE TITLE
The problem with the repository of prac

### ISSUE THREAD

**Issue by munu8** [danielnyga/prac#1]
Hello,
       When I want to download the repository of prac from the github,I found the repository is empty.
       The website is https://github.com/danielnyga/prac.git
       Could you give me a new website to download the repository of prac.
       Thanks a lot!

**Comment by mareikep** [comment]
Hello,
sorry for the delay, but the code is now available. Please find the documentation on actioncores.org or build it manually in the docs directory. 
-Mareike
